server:
  port: 8010

spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        # Add your routes here.
        - id: college_route
          uri: lb://provider-service
          predicates:
            - Path=/provider/**

    sentinel:
      transport:
        dashboard: localhost:8011
      datasource.ds1.file:
        file: "classpath: gateway.json"
        ruleType: gw-flow
